# Generated by Django 5.0.6 on 2024-07-02 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "car_name",
                    models.CharField(
                        choices=[
                            ("T5", "t5"),
                            ("M4", "m4"),
                            ("SX5", "sx5"),
                            ("B511", "B511"),
                        ],
                        default="T5",
                        max_length=20,
                        verbose_name="نام ماشین",
                    ),
                ),
                (
                    "VIN_number",
                    models.IntegerField(unique=True, verbose_name="شماره VIN"),
                ),
            ],
            options={
                "verbose_name": "خودرو",
                "verbose_name_plural": "خودرو ها",
            },
        ),
    ]
