# Generated by Django 5.0.6 on 2024-07-04 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car_module", "0004_alter_carmodel_vin_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carmodel",
            name="VIN_number",
            field=models.IntegerField(verbose_name="شماره VIN"),
        ),
    ]
